print('This are ex. of print fct. using single&double quotes, esc character')
print("We're going to the store")
print('He said "Hi"')
print('We\'re going to the store')
print('Hi '+'there')
print('Hi','there')
print('Hi '+str(5))
print('Hi',5)
print(int('8')+5)
print(float('8.5')+5)